version: '3'
services:
  ubuntu-gdbserver:
    build: .
    security_opt: # For gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "7776:22" # For ssh
      - "7777:7777" # For gdbserver
    volumes:
      - .:/work
